/**
 * Policy Admin field catalog — plain helpers with prompt → trigger → effect.
 */

export const BANDS = [
  {
    id: 'compact',
    label: 'Compact',
    rangeLabel: '< 50k',
    summary: 'Small windows (≈30–35k). Lean patches; protect history + skills.',
    exampleWindows: [30_000, 35_000, 49_000],
    defaultPreviewWindow: 35_000,
  },
  {
    id: 'standard',
    label: 'Standard',
    rangeLabel: '50k – < 100k',
    summary: 'Built-in defaults. Leave overrides empty.',
    exampleWindows: [64_000, 75_000, 99_000],
    defaultPreviewWindow: 75_000,
  },
  {
    id: 'wide',
    label: 'Wide',
    rangeLabel: '≥ 100k',
    summary: 'Large windows. More skills; mutation stays effort-capped.',
    exampleWindows: [100_000, 128_000, 200_000],
    defaultPreviewWindow: 128_000,
  },
];

/**
 * Helper shape used by the UI drawer:
 * plain, whenHigher, whenLower, example, examplePrompt, story (long narrative)
 */

/** @type {readonly object[]} */
export const WINDOW_FIELDS = [
  {
    key: 'outputRatio',
    group: '1 · Budget split',
    label: 'Output reserve',
    kind: 'ratio',
    min: 0.1,
    max: 0.4,
    step: 0.01,
    primary: true,
    budgetRole: 'output',
    shareOf: 'window',
    forLabel: 'writing the answer / patches',
    plain: 'Share of the full preview window saved for the model to write (patches, replies).',
    whenHigher: 'More writing room; less left to read code.',
    whenLower: 'More reading room; patches may get cut off.',
    example: 'Preview 35,000 · 20% would be 7,000, but Output minimum (10,240) often wins → you still see ~10,240 tokens.',
    examplePrompt: 'Apply a multi-hunk patch to AuthService and its test.',
    story:
      'Example prompt: “Update AuthService and the unit test in one patch.”\n\nWhen it matters: the model needs enough output room to emit apply_patch. If Output is too low, the reply is cut mid-patch and you burn truncation recoveries.\n\nWhat happens: Mitii reserves this % (or Output minimum, whichever is larger) first. Everything else shares what remains.\n\nStable tip: keep Output high enough for a full patch on your smallest window. Raising it forever wastes reading room.',
  },
  {
    key: 'outputMinTokens',
    group: '1 · Budget split',
    label: 'Output minimum',
    kind: 'int',
    min: 1024,
    max: 32_768,
    step: 256,
    primary: true,
    budgetRole: 'output',
    shareOf: 'window',
    forLabel: 'writing the answer / patches',
    plain: 'Never reserve fewer than this many tokens for writing — even on small windows.',
    whenHigher: 'Safer patches on small models.',
    whenLower: 'Patches may truncate mid-write.',
    example: 'On 35,000 preview, minimum 10,240 → Output shows ~10,240 tokens (~29% of window).',
    examplePrompt: 'Rewrite the full failing test body.',
    story:
      'Example prompt: “Replace the whole matcher and paste the complete test.”\n\nWhen it matters: small local models (30–35k). Percent-only output can fall below what a patch needs.\n\nWhat happens: if % × window < this minimum, Mitii uses the minimum instead.\n\nStable tip: keep ≥ 10,240 for compact. Don’t raise blindly — every extra output token steals from code/history.',
  },
  {
    key: 'toolSchemaFallbackWindowRatio',
    group: '1 · Budget split',
    label: 'Tool schemas reserve',
    kind: 'ratio',
    min: 0.05,
    max: 0.35,
    step: 0.01,
    primary: true,
    budgetRole: 'tools',
    shareOf: 'window',
    forLabel: 'tool / function definitions',
    plain: 'Share of the preview window kept for tool schemas (apply_patch, read, search, …).',
    whenHigher: 'More room for tool defs; less usable input.',
    whenLower: 'More usable input; tools may be trimmed.',
    example: 'Preview 35,000 · 20% ≈ up to 7,000 tool-schema tokens (also capped by a fixed fallback).',
    examplePrompt: 'Use tools to read files and apply_patch.',
    story:
      'Example prompt: any Agent turn that calls tools.\n\nWhen it matters: every execute run. Tools must fit in the prompt before repo/history.\n\nWhat happens: after Output is reserved, Mitii sets aside tool-schema tokens (this % of window, capped).\n\nStable tip: leave near 20% unless tools are failing to load. Cutting too low breaks the agent; raising too high starves code context.',
  },
  {
    key: 'repositoryShare',
    group: '1 · Budget split',
    label: 'Repository share',
    kind: 'ratio',
    min: 0.05,
    max: 0.5,
    step: 0.01,
    primary: true,
    budgetRole: 'repository',
    shareOf: 'usable',
    forLabel: 'code / repo context',
    plain: 'Share of usable input spent on code from the repo (not of the full window).',
    whenHigher: 'More code in the prompt.',
    whenLower: 'Less code; more Free for history/skills.',
    example: 'Usable ≈ 17,760 on a 35k preview → 25% = about 4,440 tokens of code.',
    examplePrompt: 'Find every caller of deprecated encrypt() and update them.',
    story:
      'Example prompt: “Find all callers of encrypt() and update them.”\n\nWhen it matters: tasks that need lots of code in context.\n\nWhat happens: of usable input (window minus output minus tools), this % becomes repo tokens. 25% of 17,760 ≈ 4,440 — that is what you see as Repository.\n\nStable tip: shares need not total 100%. Leftover is Free. Don’t push repo so high that history/skills starve.',
  },
  {
    key: 'conversationShare',
    group: '1 · Budget split',
    label: 'Conversation share',
    kind: 'ratio',
    min: 0.15,
    max: 0.6,
    step: 0.01,
    primary: true,
    budgetRole: 'conversation',
    shareOf: 'usable',
    forLabel: 'chat history / past tool results',
    plain: 'Share of usable input for this run’s history.',
    whenHigher: 'Remembers more of the run.',
    whenLower: 'Forgets sooner; frees space.',
    example: '40% of ~17,760 usable ≈ 7,104 history tokens on a 35k preview.',
    examplePrompt: 'Continue the same refactor — do not start over.',
    story:
      'Example prompt: “Continue the rename from the last turn.”\n\nWhen it matters: long Agent runs with many tool calls.\n\nWhat happens: this % of usable input keeps history. Too low → agent re-explores and wastes tokens. Too high → less room for code/skills.\n\nStable tip: keep near 40% on compact so the agent does not forget what it already did.',
  },
  {
    key: 'planShare',
    group: '1 · Budget split',
    label: 'Plan share',
    kind: 'ratio',
    min: 0.02,
    max: 0.15,
    step: 0.01,
    primary: true,
    budgetRole: 'plan',
    shareOf: 'usable',
    forLabel: 'the saved plan checklist',
    plain: 'Share of usable input for the approved plan text.',
    whenHigher: 'Longer plan kept in prompt.',
    whenLower: 'Shorter plan; more Free.',
    example: '6% of ~17,760 usable ≈ 1,065 plan tokens.',
    examplePrompt: 'Execute phase 2 of the saved plan.',
    story:
      'Example prompt: “Execute phase 2 of the plan.”\n\nWhen it matters: Plan → Agent handoff.\n\nWhat happens: plan text is packed up to this share of usable input.\n\nStable tip: small (≈6%) is enough. Giant plans waste tokens better spent on code.',
  },
  {
    key: 'skillsShare',
    group: '1 · Budget split',
    label: 'Skills share',
    kind: 'ratio',
    min: 0.01,
    max: 0.2,
    step: 0.01,
    primary: true,
    budgetRole: 'skills',
    shareOf: 'usable',
    forLabel: 'skill playbooks (how-to cards)',
    plain: 'Share of usable input for skill / playbook text — not % of the full 35k window.',
    whenHigher: 'More how-to text.',
    whenLower: 'Less skill text; more Free.',
    example: '5% of ~17,760 usable = 888 tokens for skills. (888 is ~2.5% of the full 35,000 window.)',
    examplePrompt: 'Follow the testing skill: failing test first, then fix.',
    story:
      'Example prompt: “Follow the testing skill — write the failing test first.”\n\nWhen it matters: runs that load process playbooks.\n\nWhat happens: Skills share is % of usable input (after Output + Tool schemas). On a 35,000 preview, usable might be ~17,760. 5% × 17,760 ≈ 888 tokens for skills. That is why you see 888 — not 5% of 35,000 (which would be 1,750).\n\nStable tip: compact often uses 5% so playbooks still fit. Raising skills forever crowds out code/history.',
  },
  {
    key: 'maxUniqueFilesPerCallCap',
    group: '1 · Budget split',
    label: 'Max files per patch',
    kind: 'int',
    min: 2,
    max: 48,
    step: 1,
    primary: true,
    countRole: 'files',
    forLabel: 'files in one apply_patch',
    plain: 'Hard ceiling on how many different files one patch may touch.',
    whenHigher: 'Bigger multi-file patches (may truncate).',
    whenLower: 'Safer smaller patches.',
    example: 'Compact often 6. Medium effort also caps around 8.',
    examplePrompt: 'Update shared types and every consumer in one patch.',
    story:
      'Example prompt: “Update the shared type and all consumers.”\n\nWhen it matters: large refactors that want one big patch.\n\nWhat happens: window math suggests a file count; this cap (and effort) clamp it.\n\nStable tip: on small windows keep ≤ 6 so patches fit in Output. Wide can leave higher — effort still caps around 8.',
  },
  {
    key: 'maxSkillsCap',
    group: '1 · Budget split',
    label: 'Max skills selected',
    kind: 'int',
    min: 1,
    max: 12,
    step: 1,
    primary: true,
    countRole: 'skills',
    forLabel: 'skill cards packed',
    plain: 'Hard max how many skill playbooks can be packed.',
    whenHigher: 'More playbooks (wide often 6).',
    whenLower: 'Fewer playbooks.',
    example: 'Wide with room → up to 6 skills.',
    examplePrompt: 'Use only skills that match this task.',
    story:
      'Example prompt: a task that spans testing + API + UI.\n\nWhen it matters: packing multiple playbooks.\n\nWhat happens: selector may pick up to this many skills, also limited by Skills share tokens.\n\nStable tip: raise on wide; keep 4 on compact so Skills share is not flooded with cards.',
  },
  {
    key: 'verificationChecksMax',
    group: '1 · Budget split',
    label: 'Verification checks (max)',
    kind: 'int',
    min: 2,
    max: 32,
    step: 1,
    primary: true,
    countRole: 'verify',
    forLabel: 'verify rounds after edits',
    plain: 'Ceiling for verify rounds after edits. The live count at small windows is often lower (starts at base) — raise the preview window on the left to see the ceiling kick in.',
    whenHigher: 'Allows more thorough verify loops on large windows.',
    whenLower: 'Harder cap; faster finish, may miss leftovers.',
    example: 'Max 16 at 35k may still show Live now = 2. At a large window, live climbs toward 16.',
    examplePrompt: 'Fix remaining type errors until verification is quiet.',
    story:
      'Example prompt: “Fix all TypeScript errors from this rename.”\n\nWhen it matters: after apply_patch, when verify still fails.\n\nWhat happens: each remaining-error repair may run another check, up to this max. The slider is the ceiling; Live now on the left (and on the tile) is what this preview window actually gets.\n\nStable tip: think QA rounds, not tokens. Too low ships broken work; too high loops forever on stuck errors.',
  },
  {
    key: 'minUniqueFilesPerCall',
    group: 'Advanced · mutation',
    label: 'Min files per patch',
    kind: 'int',
    min: 1,
    max: 16,
    step: 1,
    primary: false,
    plain: 'Floor for how many files the window formula suggests.',
    whenHigher: 'Never go below this batch size.',
    whenLower: 'Allows tiny 1-file edits.',
    example: 'Floor 2 → formula alone will not suggest 1 file.',
    examplePrompt: 'Make the smallest correct fix.',
    story: 'Rare. Leave at default unless you force larger minimum batches.',
  },
  {
    key: 'filesPerOutputTokens',
    group: 'Advanced · mutation',
    label: 'Tokens per file (scaling)',
    kind: 'number',
    min: 200,
    max: 4000,
    step: 50,
    primary: false,
    plain: 'Used to guess file count from window size. Higher = fewer files.',
    whenHigher: 'Suggests fewer files.',
    whenLower: 'Suggests more files.',
    example: '35,000 × 20% / 800 ≈ 9 files before caps.',
    examplePrompt: 'Touch as many related files as safely allowed.',
    story: 'Rare scaling knob. Prefer Max files per patch for day-to-day tuning.',
  },
  {
    key: 'maxSkillsBase',
    group: 'Advanced · skills',
    label: 'Skills base count',
    kind: 'int',
    min: 1,
    max: 8,
    step: 1,
    primary: false,
    plain: 'Starting skill count before scaling with usable input.',
    whenHigher: 'Always starts with more skills.',
    whenLower: 'Starts leaner.',
    example: 'Base 2, then add if usable input is large.',
    examplePrompt: 'Prefer a short skill set.',
    story: 'Rare. Max skills selected is usually enough.',
  },
  {
    key: 'verificationChecksBase',
    group: 'Advanced · verification',
    label: 'Verification checks (start)',
    kind: 'int',
    min: 1,
    max: 8,
    step: 1,
    primary: false,
    countRole: 'verify',
    forLabel: 'verify rounds after edits',
    plain: 'Minimum number of verify checks even on small usable input.',
    whenHigher: 'Always runs more checks.',
    whenLower: 'Fewer checks on small windows.',
    example: 'Base 2 → at least two verify passes.',
    examplePrompt: 'After edits, run verify until clean.',
    story: 'Rare. Prefer Verification checks (max) for the main ceiling.',
  },
];

/** @type {readonly object[]} */
export const LOOP_FIELDS = [
  {
    key: 'explorationRereadMinCalls',
    group: '2 · Re-reads & progress',
    label: 'Min re-read calls',
    kind: 'int',
    min: 1,
    max: 64,
    step: 1,
    primary: true,
    plain: 'After this many file reads, Mitii may treat heavy re-reading as a stall.',
    whenHigher: 'More patience (good on small windows).',
    whenLower: 'Stops re-read loops sooner.',
    example: 'Compact often 12. Wide often stays near 8.',
    examplePrompt: 'Fix the null crash in AuthService.login without rewriting unrelated files.',
    story:
      'Example prompt: “Fix the null crash in AuthService.login.”\n\nWhen it reaches this point: the task is big enough that the model opens the same files again and again (re-reads). Each re-read costs tokens and time.\n\nWhat Mitii does: once file-read calls ≥ this number (and the re-read ratio trips), it nudges “stop re-reading — patch or conclude.”\n\nStable tip: if content/window is low (compact), keep this a bit higher (e.g. 12) so it can explore, but not so high that it burns the whole budget re-opening files. Find a stable middle: enough reads to understand, not endless loops.',
  },
  {
    key: 'maxReadOnlyToolTurnsBeforeMutationNudge',
    group: '2 · Re-reads & progress',
    label: 'Read turns before mutation nudge',
    kind: 'int',
    min: 1,
    max: 32,
    step: 1,
    primary: true,
    plain: 'How many “just reading” turns before Mitii says “write the patch now.”',
    whenHigher: 'More research time.',
    whenLower: 'Forces writing sooner.',
    example: 'After 10 read turns on compact → nudge to apply_patch.',
    examplePrompt: 'Add a unit test for parseInvoice and make it pass.',
    story:
      'Example prompt: “Add a unit test for parseInvoice and make it pass.”\n\nWhen it reaches this point: the agent keeps grepping/reading and never edits.\n\nWhat Mitii does: after this many successful read/search turns in execute mode, it nudges: please apply_patch now.\n\nStable tip: small windows need a bit more research (higher). Huge windows should not explore forever (lower). Balance progress vs understanding.',
  },
  {
    key: 'maxReadOnlyMutationRetryAttempts',
    group: '2 · Re-reads & progress',
    label: 'Post-nudge read retries',
    kind: 'int',
    min: 0,
    max: 8,
    step: 1,
    primary: true,
    plain: 'Extra read turns allowed after we already said “please patch.”',
    whenHigher: 'More grace.',
    whenLower: 'Fails faster if it keeps reading.',
    example: '3 retries after the nudge, then fail.',
    examplePrompt: 'Rename getUser → fetchUser across the package.',
    story:
      'Example prompt: “Rename getUser → fetchUser everywhere.”\n\nWhen it reaches this point: we already nudged for a patch, but the model reads again “just once more.”\n\nWhat Mitii does: allows this many extra read-only turns, then fails if still no patch.\n\nStable tip: a little grace (2–3) helps on compact. Too many retries waste tokens after the decision was already made.',
  },
  {
    key: 'maxTruncationRecoveries',
    group: '2 · Re-reads & progress',
    label: 'Truncation recoveries',
    kind: 'int',
    min: 0,
    max: 8,
    step: 1,
    primary: true,
    plain: 'Retries when the answer was cut off mid-patch (ran out of output room).',
    whenHigher: 'More retries (needed on small windows).',
    whenLower: 'Fewer retries.',
    example: 'Compact often 4 because small output cuts patches short.',
    examplePrompt: 'Update five related React components.',
    story:
      'Example prompt: “Update five related components in one go.”\n\nWhen it reaches this point: Output reserve was too small; the patch JSON was truncated.\n\nWhat Mitii does: retries / asks for a smaller batch, up to this many times.\n\nStable tip: raise on compact together with Output minimum. If you keep truncating, fix Output first — retries alone burn tokens.',
  },
  {
    key: 'maxRejectedMutationRecoveries',
    group: '2 · Re-reads & progress',
    label: 'Rejected-mutation recoveries',
    kind: 'int',
    min: 0,
    max: 8,
    step: 1,
    primary: true,
    plain: 'Retries when apply_patch fails (wrong text, missing file).',
    whenHigher: 'More read→retry cycles.',
    whenLower: 'Fewer retries.',
    example: 'Stale oldText → read file → try again (counts as 1).',
    examplePrompt: 'Replace the deprecated API call in src/api/client.ts.',
    story:
      'Example prompt: “Replace the deprecated API in client.ts.”\n\nWhen it reaches this point: apply_patch is rejected (stale hunk, bad path).\n\nWhat Mitii does: allows read → fix → retry, up to this count.\n\nStable tip: compact needs more (often 4) because files change underfoot. Don’t set huge — endless reject loops waste the window.',
  },
  {
    key: 'maxRecoveredAnalysisChars',
    group: '2 · Re-reads & progress',
    label: 'Recovered analysis chars',
    kind: 'int',
    min: 64,
    max: 4000,
    step: 16,
    primary: true,
    plain: 'If a turn dumped a long essay, keep only this many characters so the next turn can still patch.',
    whenHigher: 'Keeps more notes (wide).',
    whenLower: 'Cuts essays shorter (compact).',
    example: 'Compact often 320; wide often 640.',
    examplePrompt: 'Continue — implement the fix you described.',
    story:
      'Example prompt: “Continue — implement the fix you were describing.”\n\nWhen it reaches this point: a recovered turn left a huge analysis dump in the transcript.\n\nWhat Mitii does: trims that dump to this many characters so Output/history stay usable.\n\nStable tip: on low content windows, keep this lower so the next turn can still emit a patch.',
  },
  {
    key: 'explorationRereadRatio',
    group: 'Advanced · stall',
    label: 'Re-read ratio',
    kind: 'number',
    min: 1,
    max: 10,
    step: 0.25,
    primary: false,
    plain: 'Average re-reads per unique file before a stall (with min re-read calls).',
    whenHigher: 'Allows more duplicate reads.',
    whenLower: 'Breaks loops earlier.',
    example: 'Ratio 2 with 8 unique files ≈ intervene after ~16 reads.',
    examplePrompt: 'Find where the payment webhook is validated.',
    story: 'Works with Min re-read calls. Prefer tuning Min re-read calls first.',
  },
  {
    key: 'maxExplorationStallNudges',
    group: 'Advanced · stall',
    label: 'Stall nudges before stop',
    kind: 'int',
    min: 0,
    max: 8,
    step: 1,
    primary: false,
    plain: 'How many stall warnings before the run stops.',
    whenHigher: 'More chances.',
    whenLower: '0 = stop on first stall.',
    example: '2 nudges, then stop.',
    examplePrompt: 'Implement the missing /health route.',
    story: 'Rare. Pair with Min re-read calls.',
  },
  {
    key: 'maxReadOnlyToolTurnsAfterMutationNudge',
    group: 'Advanced · progress',
    label: 'Post-mutation read turns',
    kind: 'int',
    min: 1,
    max: 16,
    step: 1,
    primary: false,
    plain: 'After a successful edit, how many more read-only turns are allowed.',
    whenHigher: 'More checking after the patch.',
    whenLower: 'Moves on sooner.',
    example: '4 reads after the first successful patch.',
    examplePrompt: 'Fix the flaky timezone test.',
    story: 'Rare day-to-day. Primary read-before-patch knobs matter more.',
  },
  {
    key: 'maxReadOnlyToolTurnsAfterMutationNudges',
    group: 'Advanced · progress',
    label: 'Post-mutation read nudges',
    kind: 'int',
    min: 0,
    max: 4,
    step: 1,
    primary: false,
    plain: 'Warnings after the first edit if the agent only keeps reading.',
    whenHigher: 'More warnings.',
    whenLower: 'Ends the mutate loop sooner.',
    example: '1 nudge then stop the first loop.',
    examplePrompt: 'Apply the lint fix and move on.',
    story: 'Rare.',
  },
  {
    key: 'maxIncompleteAnswerRecoveries',
    group: 'Advanced · retries',
    label: 'Incomplete-answer recoveries',
    kind: 'int',
    min: 0,
    max: 8,
    step: 1,
    primary: false,
    plain: 'Retries when the model says almost nothing and calls no tools.',
    whenHigher: 'More “please continue” nudges.',
    whenLower: 'Stops sooner.',
    example: 'Empty reply → nudge to call a tool or finish.',
    examplePrompt: 'What does migrateUsers do? Cite the file.',
    story: 'Rare.',
  },
  {
    key: 'maxUnfulfilledExecuteRecoveries',
    group: 'Advanced · retries',
    label: 'Unfulfilled-execute recoveries',
    kind: 'int',
    min: 0,
    max: 8,
    step: 1,
    primary: false,
    plain: 'Retries when the agent explains a fix but never writes the patch.',
    whenHigher: 'More “please patch” nudges.',
    whenLower: 'Stops sooner.',
    example: 'Long diagnosis, no apply_patch → nudge.',
    examplePrompt: 'Implement the missing export.',
    story: 'Rare.',
  },
  {
    key: 'maxMustReadNudges',
    group: 'Advanced · retries',
    label: 'Must-read nudges',
    kind: 'int',
    min: 0,
    max: 4,
    step: 1,
    primary: false,
    plain: 'How many times to block an edit until required files were read.',
    whenHigher: 'Stricter “read first.”',
    whenLower: 'Allows edits sooner.',
    example: 'Must read AuthService.ts before patching it.',
    examplePrompt: 'Only edit the plan’s must-read files.',
    story: 'Rare.',
  },
  {
    key: 'verificationRepairModelCallReserveRatio',
    group: 'Advanced · verify repair',
    label: 'Repair model-call reserve',
    kind: 'ratio',
    min: 0,
    max: 1,
    step: 0.05,
    primary: false,
    plain: 'Share of model-call budget saved for fixing errors after verification.',
    whenHigher: 'More room to fix later.',
    whenLower: 'Spends more on the first pass.',
    example: '25% of 64 calls ≈ 16 kept for repairs.',
    examplePrompt: 'Refactor and keep tests green.',
    story: 'Rare.',
  },
  {
    key: 'maxVerificationRepairAttempts',
    group: 'Advanced · verify repair',
    label: 'Max verification repairs',
    kind: 'int',
    min: 0,
    max: 24,
    step: 1,
    primary: false,
    plain: 'Max times to try fixing remaining errors after verify fails.',
    whenHigher: 'More fix rounds.',
    whenLower: 'Gives up sooner.',
    example: 'Cap 6 repair loops.',
    examplePrompt: 'Fix all TypeScript errors from the rename.',
    story: 'Rare. Prefer Verification checks (max) for the check ceiling.',
  },
  {
    key: 'maxStalledVerificationRepairs',
    group: 'Advanced · verify repair',
    label: 'Stalled repair stop',
    kind: 'int',
    min: 1,
    max: 8,
    step: 1,
    primary: false,
    plain: 'Stop repairing if verify keeps failing with no progress.',
    whenHigher: 'Tries longer.',
    whenLower: 'Stops sooner when stuck.',
    example: '3 flat verifies → stop.',
    examplePrompt: 'Keep iterating until tsc is clean.',
    story: 'Rare.',
  },
  {
    key: 'defaultPreferredBatchSize',
    group: 'Advanced · batch',
    label: 'Preferred batch size',
    kind: 'int',
    min: 1,
    max: 32,
    step: 1,
    primary: false,
    plain: 'Fallback preferred files per patch when the grant does not say.',
    whenHigher: 'Prefers bigger batches.',
    whenLower: 'Prefers smaller batches.',
    example: 'Preferred 4 files.',
    examplePrompt: 'Update all call sites of formatDate.',
    story: 'Rare.',
  },
  {
    key: 'defaultMaxPatchesPerCall',
    group: 'Advanced · batch',
    label: 'Max patches per call',
    kind: 'int',
    min: 1,
    max: 64,
    step: 1,
    primary: false,
    plain: 'Hard max hunks in one apply_patch when the grant is silent.',
    whenHigher: 'Bigger patches allowed.',
    whenLower: 'Smaller patches.',
    example: 'Cap 16 hunks.',
    examplePrompt: 'Apply mechanical import fixes.',
    story: 'Rare.',
  },
];

export function asNumberRecord(obj) {
  const next = {};
  for (const [key, value] of Object.entries(obj ?? {})) {
    if (typeof value === 'number' && Number.isFinite(value)) next[key] = value;
  }
  return next;
}
