export { createMitiiClient, MitiiClient } from './client';
export type { CreateMitiiClientOptions } from './client';

export { MitiiRun, isRunEvent, isTerminalRunEvent, isSuspendedRunEvent } from './run';
export type { AgentRunResult, RunEvent } from './run';

export {
  mitiiStartInputSchema,
  mitiiResumeInputSchema,
  mitiiConversationMessageSchema,
  mitiiImageAttachmentSchema,
  toAgentEngineStartInput,
  MITII_AUTONOMY_PRESETS,
  mitiiAutonomyPresetSchema,
  resolveAutonomyPreset,
} from './contracts';
export type {
  MitiiStartInput,
  MitiiResumeInput,
  MitiiStartDefaults,
  MitiiConversationMessage,
  MitiiImageAttachment,
  MitiiAutonomyPreset,
  AgentMode,
  AgentRunBudget,
  RepositoryStateReference,
  UserRequestOrigin,
} from './contracts';

export {
  MitiiSdkError,
  MITII_SDK_ERROR_CODES,
  mapToSdkError,
} from './errors';
export type { MitiiSdkErrorCode } from './errors';

export {
  createDefaultSkillsCatalog,
  DEFAULT_HOST_SKILLS,
} from './defaultSkills';

/** Re-export selected V8 composition helpers for advanced host wiring. */
export {
  composeReadOnlyAgentEngine,
  EchoLlmPort,
  OpenAiCompatibleLlmPort,
  AnthropicLlmPort,
  GeminiLlmPort,
  InMemoryRepositoryStateStore,
  InMemoryRunCheckpointStore,
  FileRunCheckpointStore,
  FileVerificationRecordStore,
  InMemoryVerificationRecordStore,
  InMemorySkillsCatalog,
  SkillsPipeline,
  SKILLS_SCHEMA_VERSION,
  RepositoryStatePipeline,
  publishRepositoryStateInputSchema,
  REPOSITORY_STATE_SCHEMA_VERSION,
  AGENT_ENGINE_SCHEMA_VERSION,
  PLANNING_SCHEMA_VERSION,
  agentEngineStartInputSchema,
  agentEngineResumeInputSchema,
  agentRunResultSchema,
  runEvidenceSchema,
  planArtifactSchema,
  planStrategyDecisionSchema,
  planningInputSchema,
  planningResultSchema,
  discoveryBriefSchema,
  taskListSchema,
  TASK_LIST_SCHEMA_VERSION,
  parseTaskListMarkdown,
  serializeTaskListMarkdown,
  serializeTaskListForPrompt,
  serializeTaskListGuidance,
  taskListProgress,
  runEventSchema,
  ToolRuntimePipeline,
  VerificationPipeline,
  WorkspaceFileSystemManifestReader,
  InMemoryManifestReader,
  InMemoryDiagnosticsAdapter,
  NodeWorkspaceFileSystemAdapter,
  NodeProcessAdapter,
  NodeNetworkAdapter,
  NodeGitAdapter,
  ToolRegistry,
  createBuiltinToolRegistry,
  defineTool,
  DEFAULT_TOOL_DEFINITIONS,
  deriveWindowPolicy,
  mergeWindowBudgetPolicy,
  resolveWindowBudgetPolicy,
  DEFAULT_WINDOW_BUDGET_POLICY,
  WINDOW_BUDGET_POLICY,
  WINDOW_BUDGET_SCHEMA_VERSION,
  WINDOW_BUDGET_EFFORTS,
  DEFAULT_WINDOW_BUDGET_EFFORT,
  WINDOW_BUDGET_EFFORT_OVERLAY,
  resolveWindowBudgetEffort,
  WINDOW_BUDGET_BANDS,
  WINDOW_BUDGET_BAND_CEILINGS,
  WINDOW_BUDGET_BAND_TABLE,
  resolveWindowBudgetBand,
  windowBudgetBandDefinition,
  listWindowBudgetBands,
  windowBudgetInputSchema,
  windowBudgetPolicySchema,
  windowBudgetPolicyOverridesSchema,
  windowPolicySchema,
  AGENT_ENGINE_THRESHOLDS,
  resolveAgentEngineThresholds,
  agentEngineThresholdsSchema,
  agentEngineThresholdsOverridesSchema,
  resolveLoopPolicyThresholds,
  resolveLoopPolicyBandThresholds,
  LOOP_POLICY_WINDOW_BANDS,
  LOOP_POLICY_WINDOW_BAND_CEILINGS,
  LOOP_POLICY_WINDOW_BAND_TABLE,
  resolveLoopPolicyWindowBand,
  loopPolicyWindowBandDefinition,
  listLoopPolicyWindowBands,
  POLICY_LAB_SCHEMA_VERSION,
  policyLabFileSchema,
  EMPTY_POLICY_LAB,
  parsePolicyLabFile,
  tryParsePolicyLabFile,
  resolvePolicyLabOverrides,
  mergeLabUnderHostOverrides,
  promotePolicyLabToShip,
  labLoopDeltas,
  labWindowDeltas,
} from '@mitii/v8';
export type {
  LlmPort,
  AgentEngineStartInput,
  AgentEngineResumeInput,
  AgentEngineThresholds,
  AgentEngineThresholdsOverrides,
  LoopPolicyWindowBand,
  LoopPolicyWindowBandDefinition,
  ResolveLoopPolicyThresholdsInput,
  ResolvedLoopPolicy,
  PolicyLabFile,
  ResolvePolicyLabOverridesInput,
  ResolvedPolicyLabOverrides,
  PromotePolicyLabInput,
  PromotePolicyLabResult,
  ComposeReadOnlyAgentEngineOptions,
  PublishRepositoryStateInput,
  PublishRepositoryStateResult,
  RepositoryStateDescriptor,
  WorkspaceIndexingPipelineResult,
  SkillBody,
  SkillDescriptor,
  SkillIndexEntry,
  SkillsCatalogPort,
  PlanArtifact,
  PlanStrategyDecision,
  PlanningInput,
  PlanningResult,
  DiscoveryBrief,
  TaskList,
  TaskItem,
  TaskItemStatus,
  ModelCapabilities,
  ModelEvent,
  ModelRequest,
  ModelToolDefinition,
  RegisteredTool,
  ToolDefinition,
  VerificationResult,
  VerificationRecord,
  VerificationRecordStorePort,
  DiagnosticsPort,
  DiagnosticItem,
  GitPort,
  CodeNavigationPort,
  CodeNavigationQuery,
  AgentRunCheckpoint,
  AgentEngineRunCheckpointStorePort,
  PendingApprovalState,
  RunEvidence,
  RunEvidenceIssue,
  OpenAiCompatibleLlmPortConfig,
  OpenAiCompatibleAuthHeader,
  AnthropicLlmPortConfig,
  GeminiLlmPortConfig,
  WindowBudgetInput,
  WindowBudgetPolicy,
  WindowBudgetPolicyOverrides,
  WindowPolicy,
  WindowBudgetEffort,
  WindowBudgetBand,
  WindowBudgetBandDefinition,
  ResolveWindowBudgetPolicyInput,
  ResolvedWindowBudgetPolicy,
} from '@mitii/v8';
