export const DEFAULT_MAX_MODEL_CALLS = 8;
export const DEFAULT_MAX_TOOL_CALLS = 20;
export const DEFAULT_MAX_LOOP_ITERATIONS = 12;
export const DEFAULT_MAX_WALL_TIME_MS = 120_000;
export const DEFAULT_TOOL_RESULT_PREVIEW_CHARS = 4_000;
