export const DEFAULT_MAX_MODEL_CALLS = 32;
export const DEFAULT_MAX_TOOL_CALLS = 64;
export const DEFAULT_MAX_LOOP_ITERATIONS = 48;
export const DEFAULT_MAX_WALL_TIME_MS = 300_000;
export const DEFAULT_TOOL_RESULT_PREVIEW_CHARS = 4_000;
