export const DEFAULT_MAX_MODEL_CALLS = 16;
export const DEFAULT_MAX_TOOL_CALLS = 48;
export const DEFAULT_MAX_LOOP_ITERATIONS = 24;
export const DEFAULT_MAX_WALL_TIME_MS = 180_000;
export const DEFAULT_TOOL_RESULT_PREVIEW_CHARS = 4_000;
