import type { WindowBudgetPolicy } from "./contracts";

/**
 * Default proportional policy. Hosts may override any field.
 * Ratios are of the named base (window or usable input), not magic counts.
 */
export const DEFAULT_WINDOW_BUDGET_POLICY: WindowBudgetPolicy = {
  outputRatio: 0.1,
  outputMinTokens: 1_024,
  outputMaxTokens: 8_192,
  outputWindowCapRatio: 0.2,
  toolSchemaFallbackTokens: 8_000,
  toolSchemaFallbackWindowRatio: 0.2,
  minimumUsableInputTokens: 2_048,
  loopSafetyRatio: 0.94,
  repositoryShare: 0.28,
  conversationShare: 0.4,
  planShare: 0.06,
  skillsShare: 0.04,
  planTokensCap: 8_000,
  skillsTokensCap: 2_400,
  repositoryTokensCap: 64_000,
  compactionWarnRatio: 0.7,
  compactionAutoRatio: 0.8,
  compactionHardRatio: 0.92,
  keepRecentToolResultsBase: 3,
  keepRecentToolResultsPerUsable: 8_000,
  keepRecentToolResultsMax: 16,
  compactedToolResultCharsBase: 400,
  compactedToolResultCharsPerUsable: 40,
  compactedToolResultCharsMax: 4_000,
  filesPerOutputTokens: 800,
  minUniqueFilesPerCall: 2,
  maxUniqueFilesPerCallCap: 8,
  patchPayloadOutputRatio: 0.6,
  charsPerOutputToken: 3,
  requireBatchedBelowOutputTokens: 4_096,
  visiblePlanMinUsableTokens: 40_000,
  changeImpactMinUsableTokens: 40_000,
  diagnosticStepsBase: 2,
  diagnosticStepsPerUsable: 20_000,
  diagnosticStepsMax: 8,
  maxModelCallsPerUsable: 2_500,
  maxModelCallsMin: 16,
  maxModelCallsMax: 48,
  maxSkillsBase: 1,
  maxSkillsPerUsable: 30_000,
  maxSkillsCap: 4,
  verificationChecksBase: 2,
  verificationChecksPerUsable: 40_000,
  verificationChecksMax: 8,
};
