import type { WindowBudgetPolicy } from "./contracts";

/**
 * Default proportional policy. Hosts may override any field.
 * Ratios are of the named base (window or usable input), not magic counts.
 */
export const DEFAULT_WINDOW_BUDGET_POLICY: WindowBudgetPolicy = {
  outputRatio: 0.1,
  outputMinTokens: 1_024,
  outputMaxTokens: 8_192,
  outputWindowCapRatio: 0.2,
  toolSchemaFallbackTokens: 8_000,
  toolSchemaFallbackWindowRatio: 0.2,
  minimumUsableInputTokens: 2_048,
  loopSafetyRatio: 0.94,
  repositoryShare: 0.28,
  conversationShare: 0.4,
  planShare: 0.06,
  skillsShare: 0.04,
  planTokensCap: 8_000,
  skillsTokensCap: 2_400,
  repositoryTokensCap: 64_000,
  compactionWarnRatio: 0.7,
  compactionAutoRatio: 0.8,
  compactionHardRatio: 0.92,
  keepRecentToolResultsRatio: 0.00008,
  keepRecentToolResultsMin: 3,
  keepRecentToolResultsMax: 16,
  compactedToolResultCharsRatio: 0.006,
  compactedToolResultCharsMin: 400,
  compactedToolResultCharsMax: 4_000,
  compactedToolArgumentCharsRatio: 0.003,
  compactedToolArgumentCharsMin: 256,
  compactedToolArgumentCharsMax: 2_000,
  toolResultContentCharsRatio: 0.015,
  toolResultContentCharsMin: 2_000,
  toolResultContentCharsMax: 24_000,
  droppedTurnSummaryCharsRatio: 0.01,
  droppedTurnSummaryCharsMin: 1_200,
  droppedTurnSummaryCharsMax: 8_000,
  establishedFactCharsRatio: 0.002,
  establishedFactCharsMin: 220,
  establishedFactCharsMax: 900,
  establishedFactCountRatio: 0.00015,
  establishedFactCountMin: 12,
  establishedFactCountMax: 48,
  establishedFactReinjectCharsRatio: 0.012,
  establishedFactReinjectCharsMin: 1_600,
  establishedFactReinjectCharsMax: 8_000,
  memoryReinjectCharsRatio: 0.006,
  memoryReinjectCharsMin: 800,
  memoryReinjectCharsMax: 4_000,
  filesPerOutputTokens: 800,
  minUniqueFilesPerCall: 2,
  maxUniqueFilesPerCallCap: 8,
  patchPayloadOutputRatio: 0.6,
  charsPerOutputToken: 3,
  requireBatchedBelowOutputTokens: 4_096,
  visiblePlanMinUsableTokens: 8_192,
  changeImpactMinUsableTokens: 8_192,
  visiblePlanMinUsableRatio: 0.35,
  changeImpactMinUsableRatio: 0.35,
  maxPatchesPerCallCap: 12,
  diagnosticStepsBase: 2,
  diagnosticStepsPerUsable: 20_000,
  diagnosticStepsMax: 8,
  maxModelCallsPerUsable: 2_500,
  maxModelCallsMin: 48,
  maxModelCallsMax: 96,
  maxSkillsBase: 2,
  maxSkillsPerUsable: 12_000,
  maxSkillsCap: 4,
  verificationChecksBase: 2,
  verificationChecksPerUsable: 40_000,
  verificationChecksMax: 8,
};
