export const DEFAULT_CHANGE_IMPACT_MAXIMUM_HOPS = 3;
export const DEFAULT_CHANGE_IMPACT_MAXIMUM_AFFECTED_NODES = 80;
export const DEFAULT_CHANGE_IMPACT_MAXIMUM_PACKAGES = 20;
export const DEFAULT_CHANGE_IMPACT_MAXIMUM_EVIDENCE_PER_NODE = 5;
