import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';

import type { McpToolResultEvent } from '@mitii/mcp';

import { elementsToSvg } from '../shared/excalidrawSvg.js';

function mitiiDir(workspaceRoot: string): string {
  return join(workspaceRoot, '.mitii');
}

export interface ExcalidrawArtifactPaths {
  dir: string;
  excalidrawPath: string;
  svgPath: string;
  mdPath: string;
  docsMdPath?: string;
  checkpointId?: string;
  relativeExcalidraw: string;
  relativeSvg: string;
  relativeMd: string;
  relativeDocsMd?: string;
}

export interface ExcalidrawPersistResult {
  paths: ExcalidrawArtifactPaths;
  svg: string;
  title: string;
}

/**
 * Persist a successful Excalidraw `create_view` as:
 * - `.mitii/artifacts/excalidraw/<stamp>-<id>/diagram.excalidraw`
 * - `diagram.svg` (host-rendered preview)
 * - `diagram.md` (embeds SVG + links to source)
 * - optional `docs/diagrams/<slug>.md` when `docs/` exists
 */
export function persistExcalidrawFromToolResult(options: {
  workspaceRoot: string;
  event: McpToolResultEvent;
  threadId?: string;
}): ExcalidrawPersistResult | undefined {
  if (options.event.toolName !== 'create_view') return undefined;
  if (options.event.result.isError) return undefined;

  const elements =
    parseElementsArg(options.event.args) ??
    parseElementsFromResult(options.event.result);
  if (!elements?.length) return undefined;

  const checkpointId = extractCheckpointId(options.event.result);
  const stamp = new Date()
    .toISOString()
    .replace(/[:.]/g, '-')
    .replace('T', '_')
    .slice(0, 19);
  const folderName = `${stamp}${checkpointId ? `-${checkpointId.slice(0, 10)}` : ''}`;
  const dir = join(
    mitiiDir(options.workspaceRoot),
    'artifacts',
    'excalidraw',
    folderName,
  );
  mkdirSync(dir, { recursive: true });

  const title = inferTitle(elements) || 'Architecture diagram';
  const excalidrawDoc = {
    type: 'excalidraw',
    version: 2,
    source: 'mitii',
    elements,
    appState: {
      viewBackgroundColor: '#ffffff',
      gridSize: null,
    },
    files: {},
  };

  const excalidrawPath = join(dir, 'diagram.excalidraw');
  const svgPath = join(dir, 'diagram.svg');
  const mdPath = join(dir, 'diagram.md');
  const svg = elementsToSvg(elements, title);

  writeFileSync(excalidrawPath, `${JSON.stringify(excalidrawDoc, null, 2)}\n`, 'utf8');
  writeFileSync(svgPath, svg, 'utf8');

  const mdBody = buildDiagramMarkdown({
    title,
    checkpointId,
    svgRel: './diagram.svg',
    excalidrawRel: './diagram.excalidraw',
    threadId: options.threadId,
  });
  writeFileSync(mdPath, mdBody, 'utf8');

  // Always write a referencable MD under docs/diagrams/ so requirements /
  // design docs can link a stable path outside `.mitii/`.
  const docsDir = join(options.workspaceRoot, 'docs', 'diagrams');
  mkdirSync(docsDir, { recursive: true });
  const slug = slugify(title);
  const docsMdPath = join(docsDir, `${slug}-${stamp.slice(0, 10)}.md`);
  const relSvg = relative(docsDir, svgPath).replace(/\\/g, '/');
  const relExcalidraw = relative(docsDir, excalidrawPath).replace(/\\/g, '/');
  writeFileSync(
    docsMdPath,
    buildDiagramMarkdown({
      title,
      checkpointId,
      svgRel: relSvg.startsWith('.') ? relSvg : `./${relSvg}`,
      excalidrawRel: relExcalidraw.startsWith('.')
        ? relExcalidraw
        : `./${relExcalidraw}`,
      threadId: options.threadId,
    }),
    'utf8',
  );

  // Stable pointer for "latest diagram" references.
  const latestMdPath = join(
    mitiiDir(options.workspaceRoot),
    'artifacts',
    'excalidraw',
    'LATEST.md',
  );
  writeFileSync(
    latestMdPath,
    buildDiagramMarkdown({
      title,
      checkpointId,
      svgRel: relative(dirname(latestMdPath), svgPath).replace(/\\/g, '/'),
      excalidrawRel: relative(dirname(latestMdPath), excalidrawPath).replace(
        /\\/g,
        '/',
      ),
      threadId: options.threadId,
    }),
    'utf8',
  );

  const toRel = (abs: string) =>
    relative(options.workspaceRoot, abs).replace(/\\/g, '/');

  return {
    paths: {
      dir,
      excalidrawPath,
      svgPath,
      mdPath,
      ...(docsMdPath ? { docsMdPath } : {}),
      ...(checkpointId ? { checkpointId } : {}),
      relativeExcalidraw: toRel(excalidrawPath),
      relativeSvg: toRel(svgPath),
      relativeMd: toRel(mdPath),
      ...(docsMdPath ? { relativeDocsMd: toRel(docsMdPath) } : {}),
    },
    svg,
    title,
  };
}

function buildDiagramMarkdown(params: {
  title: string;
  checkpointId?: string;
  svgRel: string;
  excalidrawRel: string;
  threadId?: string;
}): string {
  const lines = [
    `# ${params.title}`,
    '',
    `Generated by Mitii + Excalidraw MCP${params.threadId ? ` (thread \`${params.threadId}\`)` : ''}.`,
    '',
    `![${params.title}](${params.svgRel})`,
    '',
    '## Files',
    '',
    `- SVG preview: \`${params.svgRel}\``,
    `- Excalidraw source: \`${params.excalidrawRel}\``,
  ];
  if (params.checkpointId) {
    lines.push(`- Checkpoint id: \`${params.checkpointId}\``);
  }
  lines.push('', 'Open the \`.excalidraw\` file in [excalidraw.com](https://excalidraw.com) or any Excalidraw-compatible editor.', '');
  return `${lines.join('\n')}\n`;
}

function parseElementsArg(args: unknown): unknown[] | undefined {
  if (!args || typeof args !== 'object') return undefined;
  const elements = (args as { elements?: unknown }).elements;
  if (Array.isArray(elements)) return elements;
  if (typeof elements === 'string') {
    try {
      const parsed = JSON.parse(elements) as unknown;
      return Array.isArray(parsed) ? parsed : undefined;
    } catch {
      return undefined;
    }
  }
  return undefined;
}

function parseElementsFromResult(
  result: McpToolResultEvent['result'],
): unknown[] | undefined {
  const structured = result.structuredContent;
  if (structured && typeof structured === 'object') {
    const fromStructured = parseElementsArg(structured);
    if (fromStructured?.length) return fromStructured;
  }
  if (result.content && typeof result.content === 'object') {
    return parseElementsArg(result.content);
  }
  return undefined;
}

function extractCheckpointId(result: McpToolResultEvent['result']): string | undefined {
  const structured = result.structuredContent;
  if (structured && typeof structured === 'object') {
    const id = (structured as { checkpointId?: unknown }).checkpointId;
    if (typeof id === 'string' && id.trim()) return id.trim();
  }
  const content = result.content;
  if (typeof content === 'string') {
    const match = /checkpoint[^\w]*([a-f0-9]{10,})/i.exec(content);
    if (match?.[1]) return match[1];
  }
  if (content && typeof content === 'object' && !Array.isArray(content)) {
    const id = (content as { checkpointId?: unknown }).checkpointId;
    if (typeof id === 'string' && id.trim()) return id.trim();
  }
  return undefined;
}

function inferTitle(elements: unknown[]): string | undefined {
  for (const el of elements) {
    if (!el || typeof el !== 'object') continue;
    const typed = el as { type?: string; text?: string };
    if (typed.type === 'text' && typeof typed.text === 'string' && typed.text.trim()) {
      return typed.text.trim().slice(0, 80);
    }
  }
  return undefined;
}

function slugify(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 48) || 'diagram'
  );
}

export { elementsToSvg } from '../shared/excalidrawSvg.js';

