import {
  DEFAULT_EMBED_MAX_CHARS,
  DEFAULT_MAX_ACCESS_LOG,
  DEFAULT_MAX_DERIVED_CONCEPTS,
  DEFAULT_MAX_MEMORY_FACTS,
  DEFAULT_MEMORY_BUDGET_TOKENS,
  DEFAULT_MEMORY_IMPORTANCE,
  DEFAULT_MIN_MEMORY_SCORE,
  DEFAULT_RETENTION_DAYS,
} from "./defaults";

export const MEMORY_THRESHOLDS = {
  defaultBudgetTokens: DEFAULT_MEMORY_BUDGET_TOKENS,
  defaultMaxFacts: DEFAULT_MAX_MEMORY_FACTS,
  minimumRelevanceScore: DEFAULT_MIN_MEMORY_SCORE,
  defaultRetentionDays: DEFAULT_RETENTION_DAYS,
  defaultImportance: DEFAULT_MEMORY_IMPORTANCE,
  maxDerivedConcepts: DEFAULT_MAX_DERIVED_CONCEPTS,
  bm25K1: 1.2,
  bm25B: 0.75,
  synonymWeight: 0.7,
  prefixIdfScale: 0.5,
  minPrefixTermLength: 3,
  rrfK: 60,
  bm25StreamWeight: 0.55,
  fileStreamWeight: 0.25,
  vectorStreamWeight: 0.2,
  maxFactsPerSource: 3,
  bm25RelativeFloor: 0.2,
  /** Drop BM25 hits that cover fewer distinct query terms than this (or the query size, whichever is smaller). */
  minCoveredQueryTerms: 2,
  jaccardSupersede: 0.7,
  dedupWindowMs: 5 * 60 * 1000,
  maxAccessLog: DEFAULT_MAX_ACCESS_LOG,
  embedMaxChars: DEFAULT_EMBED_MAX_CHARS,
  retentionLambda: 0.01,
  retentionSigma: 0.3,
  retentionMix: 0.35,
  profileMaxFiles: 5,
  profileMaxConcepts: 8,
  profileMinBudgetTokens: 24,
  vectorMinScore: 0.15,
} as const;
